#!/bin/sh

stop() {
    sudo rmmod kflag
}

start() {
    sudo insmod /home/vagrant/kflag/kflag.ko
    # https://bugs.launchpad.net/ubuntu/+source/procps/+bug/1157643/comments/84
    sudo /sbin/sysctl -q --system
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        stop
        start
        ;;
    *)
    echo "Usage: $0 {start|stop|restart}"
esac
